### ISSUE TITLE
product page view needs some changes.

### ISSUE THREAD

**Issue by mahdi-eth** [mahdi-eth/Hitek#6]
**product page view needs some changes.**

1. These icons are not the same as figma's icons. 

![Screenshot 2023-03-06 142108](https://user-images.githubusercontent.com/99660553/223091535-0d9396a0-db0b-4d7a-aec7-6ef2cf1f794e.jpg)

2. This button must change color when is hovered. You can check the code for the button in the header which does this and copy paste its code.

![Screenshot 2023-03-06 142152](https://user-images.githubusercontent.com/99660553/223091768-86b61c77-6eef-49c1-893c-8263e973b37c.jpg)

3. These cards must not have shadow and their width must be equal.

![Screenshot 2023-03-06 142221](https://user-images.githubusercontent.com/99660553/223092199-0701af5f-516e-4d6a-bd11-01f40cc2253a.jpg)

**Comment by mahdi-eth** [comment]
@Mohammad-dn Fix these please.

**Comment by Mohammad-dn** [comment]
Fix shode hesabesh kon @mahdi-eth

**Comment by mahdi-eth** [comment]
Issues have bees fixed.💯
